// Reference data (categories, zones) and SAMPLE offers for development,
// tests and demos. The venues are fictional. Production seeds reference data
// only (see seed.ts); real partners are entered by the club team.

type Locale = "pt-PT" | "pt-BR" | "es" | "en";
export type L10n<T = string> = Record<Locale, T>;

export const categories: { slug: string; icon: string; tone: string; name: L10n }[] = [
  { slug: "restaurants", icon: "fork", tone: "ci-roof", name: { "pt-PT": "Restaurantes", "pt-BR": "Restaurantes", es: "Restaurantes", en: "Restaurants" } },
  { slug: "bars", icon: "glass", tone: "ci-violet", name: { "pt-PT": "Bares", "pt-BR": "Bares", es: "Bares", en: "Bars" } },
  { slug: "events", icon: "ticket", tone: "ci-sky", name: { "pt-PT": "Eventos", "pt-BR": "Eventos", es: "Eventos", en: "Events" } },
  { slug: "culture", icon: "museum", tone: "ci-sun", name: { "pt-PT": "Cultura", "pt-BR": "Cultura", es: "Cultura", en: "Culture" } },
  { slug: "leisure", icon: "wave", tone: "ci-leaf", name: { "pt-PT": "Lazer", "pt-BR": "Lazer", es: "Ocio", en: "Leisure" } },
];

export const zones: { slug: string; name: L10n }[] = [
  { slug: "ribeira", name: { "pt-PT": "Ribeira e Baixa", "pt-BR": "Ribeira e Baixa", es: "Ribeira y Baixa", en: "Ribeira and Baixa" } },
  { slug: "boavista", name: { "pt-PT": "Cedofeita e Boavista", "pt-BR": "Cedofeita e Boavista", es: "Cedofeita y Boavista", en: "Cedofeita and Boavista" } },
  { slug: "foz", name: { "pt-PT": "Foz e Matosinhos", "pt-BR": "Foz e Matosinhos", es: "Foz y Matosinhos", en: "Foz and Matosinhos" } },
  { slug: "gaia", name: { "pt-PT": "Vila Nova de Gaia", "pt-BR": "Vila Nova de Gaia", es: "Vila Nova de Gaia", en: "Vila Nova de Gaia" } },
];

type OfferCopy = {
  title: string;
  summary: string;
  description: string;
  schedule: string;
  conditions: string[];
};

export type SampleOffer = {
  slug: string;
  category: string;
  zone: string;
  featured?: boolean;
  discount: { type: "PERCENT" | "AMOUNT" | "TWO_FOR_ONE"; value?: number };
  maxPeople?: number;
  art: string;
  venue: {
    name: string;
    address: string;
    postalCode: string;
    city: string;
    neighbourhood: string;
    latitude: number;
    longitude: number;
    phone?: string;
  };
  copy: L10n<OfferCopy>;
};

export const sampleOffers: SampleOffer[] = [
  {
    slug: "tasca-da-viela",
    category: "restaurants",
    zone: "ribeira",
    featured: true,
    discount: { type: "PERCENT", value: 30 },
    maxPeople: 4,
    art: "tasca",
    venue: { name: "Tasca da Viela", address: "Rua da Viela 23", postalCode: "4050-253", city: "Porto", neighbourhood: "Ribeira", latitude: 41.1411, longitude: -8.6127, phone: "+351 220 000 101" },
    copy: {
      "pt-PT": {
        title: "30% no total da conta",
        summary: "Ao jantar, de segunda a quinta",
        description: "Petiscos do norte numa viela de granito junto ao rio. Tripas, bacalhau à Gomes de Sá e a francesinha da casa, servida em pratos de azulejo antigo.",
        schedule: "Segunda a quinta, ao jantar · 19:00–23:00",
        conditions: ["Não acumula com outras promoções", "Reserva recomendada à sexta"],
      },
      "pt-BR": {
        title: "30% no total da conta",
        summary: "No jantar, de segunda a quinta",
        description: "Petiscos do norte de Portugal num beco de granito perto do rio. Tripas, bacalhau à Gomes de Sá e a francesinha da casa, servida em pratos de azulejo antigo.",
        schedule: "Segunda a quinta, no jantar · 19h–23h",
        conditions: ["Não cumulativo com outras promoções", "Recomendamos reservar às sextas"],
      },
      es: {
        title: "30 % en el total de la cuenta",
        summary: "En la cena, de lunes a jueves",
        description: "Tapas del norte en un callejón de granito junto al río. Callos, bacalao a la Gomes de Sá y la francesinha de la casa, servida en platos de azulejo antiguo.",
        schedule: "De lunes a jueves, en la cena · 19:00–23:00",
        conditions: ["No acumulable con otras promociones", "Se recomienda reservar los viernes"],
      },
      en: {
        title: "30% off the whole bill",
        summary: "Dinner, Monday to Thursday",
        description: "Northern Portuguese small plates in a granite alley by the river. Tripe, Gomes de Sá salt cod and the house francesinha, served on old azulejo plates.",
        schedule: "Monday to Thursday, dinner · 19:00–23:00",
        conditions: ["Can't be combined with other promotions", "Booking recommended on Fridays"],
      },
    },
  },
  {
    slug: "casa-do-bacalhau-velho",
    category: "restaurants",
    zone: "ribeira",
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 6,
    art: "ribeira",
    venue: { name: "Casa do Bacalhau Velho", address: "Rua das Flores 112", postalCode: "4050-266", city: "Porto", neighbourhood: "Baixa", latitude: 41.1438, longitude: -8.6132 },
    copy: {
      "pt-PT": {
        title: "20% em pratos principais",
        summary: "Almoço e jantar, todos os dias",
        description: "Uma casa de família dedicada ao bacalhau: à Brás, com natas, assado na brasa. A carta de vinhos do Douro também conta.",
        schedule: "Todos os dias · 12:00–15:00 e 19:00–22:30",
        conditions: ["Válido em pratos principais"],
      },
      "pt-BR": {
        title: "20% nos pratos principais",
        summary: "Almoço e jantar, todos os dias",
        description: "Uma casa de família dedicada ao bacalhau: à Brás, com natas, assado na brasa. A carta de vinhos do Douro também vale a visita.",
        schedule: "Todos os dias · 12h–15h e 19h–22h30",
        conditions: ["Válido nos pratos principais"],
      },
      es: {
        title: "20 % en platos principales",
        summary: "Comida y cena, todos los días",
        description: "Una casa familiar dedicada al bacalao: a la Brás, con nata, asado a la brasa. La carta de vinos del Duero también merece la pena.",
        schedule: "Todos los días · 12:00–15:00 y 19:00–22:30",
        conditions: ["Válido en platos principales"],
      },
      en: {
        title: "20% off main courses",
        summary: "Lunch and dinner, every day",
        description: "A family house devoted to salt cod: à Brás, with cream, grilled over coals. The Douro wine list is worth the trip too.",
        schedule: "Every day · 12:00–15:00 and 19:00–22:30",
        conditions: ["Valid on main courses"],
      },
    },
  },
  {
    slug: "francesinha-do-largo",
    category: "restaurants",
    zone: "boavista",
    discount: { type: "PERCENT", value: 25 },
    maxPeople: 2,
    art: "tasca",
    venue: { name: "Francesinha do Largo", address: "Rua de Cedofeita 301", postalCode: "4050-174", city: "Porto", neighbourhood: "Cedofeita", latitude: 41.1531, longitude: -8.6191 },
    copy: {
      "pt-PT": {
        title: "25% na francesinha da casa",
        summary: "Com batatas fritas incluídas",
        description: "Molho de receita guardada, pão de forma tostado e ovo a pedido. Uma das francesinhas mais discutidas de Cedofeita.",
        schedule: "Terça a domingo · 12:00–23:00",
        conditions: ["Até 2 francesinhas por cartão", "Não válido em take-away"],
      },
      "pt-BR": {
        title: "25% na francesinha da casa",
        summary: "Com batata frita inclusa",
        description: "Molho de receita secreta, pão de forma tostado e ovo se você quiser. Uma das francesinhas mais comentadas de Cedofeita.",
        schedule: "Terça a domingo · 12h–23h",
        conditions: ["Até 2 francesinhas por cartão", "Não vale para viagem"],
      },
      es: {
        title: "25 % en la francesinha de la casa",
        summary: "Con patatas fritas incluidas",
        description: "Salsa de receta secreta, pan de molde tostado y huevo si lo pides. Una de las francesinhas más comentadas de Cedofeita.",
        schedule: "De martes a domingo · 12:00–23:00",
        conditions: ["Hasta 2 francesinhas por tarjeta", "No válido para llevar"],
      },
      en: {
        title: "25% off the house francesinha",
        summary: "Chips included",
        description: "A closely guarded sauce, toasted bread and an egg if you ask. One of the most argued-about francesinhas in Cedofeita.",
        schedule: "Tuesday to Sunday · 12:00–23:00",
        conditions: ["Up to 2 francesinhas per card", "Not valid for takeaway"],
      },
    },
  },
  {
    slug: "petiscos-e-granito",
    category: "restaurants",
    zone: "ribeira",
    discount: { type: "TWO_FOR_ONE" },
    maxPeople: 2,
    art: "cafe",
    venue: { name: "Petiscos & Granito", address: "Rua de Miragaia 58", postalCode: "4050-387", city: "Porto", neighbourhood: "Miragaia", latitude: 41.1431, longitude: -8.6195 },
    copy: {
      "pt-PT": {
        title: "Segundo petisco oferecido",
        summary: "Na compra de um petisco",
        description: "Pataniscas, moelas, pica-pau e queijos da serra numa sala de pedra virada para o rio.",
        schedule: "Todos os dias · 17:00–00:00",
        conditions: ["Oferta do petisco de menor valor", "Um 2x1 por visita"],
      },
      "pt-BR": {
        title: "Segundo petisco grátis",
        summary: "Na compra de um petisco",
        description: "Pataniscas, moelas, pica-pau e queijos da serra num salão de pedra de frente para o rio.",
        schedule: "Todos os dias · 17h–0h",
        conditions: ["O petisco de menor valor é grátis", "Um 2 por 1 por visita"],
      },
      es: {
        title: "Segunda tapa gratis",
        summary: "Al pedir una tapa",
        description: "Buñuelos de bacalao, mollejas, pica-pau y quesos de la sierra en una sala de piedra frente al río.",
        schedule: "Todos los días · 17:00–00:00",
        conditions: ["La tapa de menor precio es gratis", "Un 2x1 por visita"],
      },
      en: {
        title: "Second small plate free",
        summary: "When you order one",
        description: "Salt cod fritters, gizzards, pica-pau and mountain cheeses in a stone room facing the river.",
        schedule: "Every day · 17:00–00:00",
        conditions: ["The cheaper plate is free", "One 2-for-1 per visit"],
      },
    },
  },
  {
    slug: "marisqueira-da-foz",
    category: "restaurants",
    zone: "foz",
    discount: { type: "PERCENT", value: 15 },
    maxPeople: 4,
    art: "ribeira",
    venue: { name: "Marisqueira da Foz", address: "Avenida do Brasil 410", postalCode: "4150-153", city: "Porto", neighbourhood: "Foz do Douro", latitude: 41.1531, longitude: -8.6792 },
    copy: {
      "pt-PT": {
        title: "15% em marisco e peixe grelhado",
        summary: "De domingo a quinta",
        description: "Amêijoas à Bulhão Pato, polvo à lagareiro e peixe do dia com vista para o mar da Foz.",
        schedule: "Domingo a quinta · 12:30–22:30",
        conditions: ["Não inclui bebidas"],
      },
      "pt-BR": {
        title: "15% em frutos do mar e peixe grelhado",
        summary: "De domingo a quinta",
        description: "Amêijoas à Bulhão Pato, polvo à lagareiro e peixe do dia com vista para o mar da Foz.",
        schedule: "Domingo a quinta · 12h30–22h30",
        conditions: ["Bebidas não incluídas"],
      },
      es: {
        title: "15 % en marisco y pescado a la brasa",
        summary: "De domingo a jueves",
        description: "Almejas a la Bulhão Pato, pulpo a la lagareiro y pescado del día con vistas al mar de Foz.",
        schedule: "De domingo a jueves · 12:30–22:30",
        conditions: ["Bebidas no incluidas"],
      },
      en: {
        title: "15% off seafood and grilled fish",
        summary: "Sunday to Thursday",
        description: "Bulhão Pato clams, lagareiro octopus and the catch of the day looking out over the sea at Foz.",
        schedule: "Sunday to Thursday · 12:30–22:30",
        conditions: ["Drinks not included"],
      },
    },
  },
  {
    slug: "tasquinha-do-mercado",
    category: "restaurants",
    zone: "foz",
    discount: { type: "AMOUNT", value: 10 },
    maxPeople: 4,
    art: "tasca",
    venue: { name: "Tasquinha do Mercado", address: "Rua Heróis de França 520", postalCode: "4450-155", city: "Matosinhos", neighbourhood: "Matosinhos", latitude: 41.1842, longitude: -8.6935 },
    copy: {
      "pt-PT": {
        title: "10 € de desconto em contas acima de 40 €",
        summary: "Peixe fresco do mercado de Matosinhos",
        description: "Sardinhas, robalo e lulas grelhadas na rua do peixe, com o carvão aceso à porta.",
        schedule: "Todos os dias · 12:00–16:00 e 19:00–23:00",
        conditions: ["Conta mínima de 40 €", "Um desconto por mesa"],
      },
      "pt-BR": {
        title: "10 € de desconto em contas acima de 40 €",
        summary: "Peixe fresco do mercado de Matosinhos",
        description: "Sardinhas, robalo e lulas grelhadas na rua do peixe, com a brasa acesa na porta.",
        schedule: "Todos os dias · 12h–16h e 19h–23h",
        conditions: ["Conta mínima de 40 €", "Um desconto por mesa"],
      },
      es: {
        title: "10 € de descuento en cuentas de más de 40 €",
        summary: "Pescado fresco del mercado de Matosinhos",
        description: "Sardinas, lubina y calamares a la brasa en la calle del pescado, con el carbón encendido en la puerta.",
        schedule: "Todos los días · 12:00–16:00 y 19:00–23:00",
        conditions: ["Cuenta mínima de 40 €", "Un descuento por mesa"],
      },
      en: {
        title: "€10 off bills over €40",
        summary: "Fresh fish from Matosinhos market",
        description: "Sardines, sea bass and squid grilled on the fish street, with the charcoal burning by the door.",
        schedule: "Every day · 12:00–16:00 and 19:00–23:00",
        conditions: ["Minimum bill of €40", "One discount per table"],
      },
    },
  },
  {
    slug: "cafe-bolhao-novo",
    category: "restaurants",
    zone: "ribeira",
    featured: true,
    discount: { type: "PERCENT", value: 15 },
    art: "cafe",
    venue: { name: "Café Bolhão Novo", address: "Rua Formosa 214", postalCode: "4000-248", city: "Porto", neighbourhood: "Baixa", latitude: 41.1497, longitude: -8.6063 },
    copy: {
      "pt-PT": {
        title: "15% em pequenos-almoços e lanches",
        summary: "Todos os dias até às 18:00",
        description: "Pastéis de nata saídos do forno, torradas de pão de forma e galões numa sala art déco ao lado do mercado.",
        schedule: "Todos os dias · 08:00–18:00",
        conditions: ["Válido na sala, não ao balcão de take-away"],
      },
      "pt-BR": {
        title: "15% no café da manhã e no lanche",
        summary: "Todos os dias até as 18h",
        description: "Pastéis de nata saindo do forno, torradas e café com leite num salão art déco ao lado do mercado.",
        schedule: "Todos os dias · 8h–18h",
        conditions: ["Válido no salão, não no balcão para viagem"],
      },
      es: {
        title: "15 % en desayunos y meriendas",
        summary: "Todos los días hasta las 18:00",
        description: "Pastéis de nata recién salidos del horno, tostadas y cafés con leche en un salón art déco junto al mercado.",
        schedule: "Todos los días · 08:00–18:00",
        conditions: ["Válido en sala, no en la barra para llevar"],
      },
      en: {
        title: "15% off breakfast and afternoon snacks",
        summary: "Every day until 18:00",
        description: "Custard tarts fresh from the oven, thick toast and milky coffees in an art deco room next to the market.",
        schedule: "Every day · 08:00–18:00",
        conditions: ["Valid at the tables, not at the takeaway counter"],
      },
    },
  },
  {
    slug: "terraco-seis",
    category: "bars",
    zone: "boavista",
    featured: true,
    discount: { type: "TWO_FOR_ONE" },
    maxPeople: 2,
    art: "bar",
    venue: { name: "Terraço Seis", address: "Rua Miguel Bombarda 66", postalCode: "4050-377", city: "Porto", neighbourhood: "Cedofeita", latitude: 41.1517, longitude: -8.6204 },
    copy: {
      "pt-PT": {
        title: "2x1 em cocktails de autor",
        summary: "Ao fim da tarde, de terça a sexta",
        description: "Um terraço no sexto andar com o Porto aos pés. Cocktails com ingredientes portugueses: ginja, vinho do Porto branco, laranja do Algarve.",
        schedule: "Terça a sexta · 18:00–20:30",
        conditions: ["Dois cocktails iguais", "Um 2x1 por cartão por visita"],
      },
      "pt-BR": {
        title: "2 por 1 em drinks autorais",
        summary: "No fim da tarde, de terça a sexta",
        description: "Um terraço no sexto andar com o Porto a seus pés. Drinks com ingredientes portugueses: ginja, vinho do Porto branco, laranja do Algarve.",
        schedule: "Terça a sexta · 18h–20h30",
        conditions: ["Dois drinks iguais", "Um 2 por 1 por cartão por visita"],
      },
      es: {
        title: "2x1 en cócteles de autor",
        summary: "Al atardecer, de martes a viernes",
        description: "Una terraza en el sexto piso con Oporto a tus pies. Cócteles con ingredientes portugueses: ginja, oporto blanco, naranja del Algarve.",
        schedule: "De martes a viernes · 18:00–20:30",
        conditions: ["Dos cócteles iguales", "Un 2x1 por tarjeta y visita"],
      },
      en: {
        title: "2-for-1 signature cocktails",
        summary: "Early evening, Tuesday to Friday",
        description: "A sixth-floor terrace with Porto at your feet. Cocktails made with Portuguese ingredients: ginja, white port, Algarve oranges.",
        schedule: "Tuesday to Friday · 18:00–20:30",
        conditions: ["Two of the same cocktail", "One 2-for-1 per card per visit"],
      },
    },
  },
  {
    slug: "caves-do-cais",
    category: "bars",
    zone: "gaia",
    discount: { type: "PERCENT", value: 15 },
    maxPeople: 4,
    art: "vinho",
    venue: { name: "Caves do Cais", address: "Cais de Gaia 120", postalCode: "4400-161", city: "Vila Nova de Gaia", neighbourhood: "Cais de Gaia", latitude: 41.1371, longitude: -8.6142 },
    copy: {
      "pt-PT": {
        title: "15% em provas de vinho do Porto",
        summary: "Provas de 3 ou 5 vinhos",
        description: "Uma cave pequena e independente no cais, com tawnies de 10 e 20 anos e vintages de pequenos produtores.",
        schedule: "Todos os dias · 11:00–20:00",
        conditions: ["Maiores de 18 anos"],
      },
      "pt-BR": {
        title: "15% em degustações de vinho do Porto",
        summary: "Degustações de 3 ou 5 vinhos",
        description: "Uma adega pequena e independente no cais, com tawnies de 10 e 20 anos e vintages de pequenos produtores.",
        schedule: "Todos os dias · 11h–20h",
        conditions: ["Maiores de 18 anos"],
      },
      es: {
        title: "15 % en catas de vino de Oporto",
        summary: "Catas de 3 o 5 vinos",
        description: "Una bodega pequeña e independiente en el muelle, con tawnies de 10 y 20 años y vintages de pequeños productores.",
        schedule: "Todos los días · 11:00–20:00",
        conditions: ["Mayores de 18 años"],
      },
      en: {
        title: "15% off port wine tastings",
        summary: "Flights of 3 or 5 wines",
        description: "A small independent cellar on the quay, pouring 10- and 20-year tawnies and vintages from small producers.",
        schedule: "Every day · 11:00–20:00",
        conditions: ["18+ only"],
      },
    },
  },
  {
    slug: "bar-do-miradouro",
    category: "bars",
    zone: "gaia",
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 4,
    art: "bar",
    venue: { name: "Bar do Miradouro", address: "Largo da Serra do Pilar 4", postalCode: "4430-210", city: "Vila Nova de Gaia", neighbourhood: "Serra do Pilar", latitude: 41.1383, longitude: -8.6082 },
    copy: {
      "pt-PT": {
        title: "20% em toda a carta",
        summary: "Ao pôr do sol sobre a ponte",
        description: "Imperiais, vinho verde e tábuas de enchidos com a melhor vista sobre a Ponte Luís I e a Ribeira.",
        schedule: "Todos os dias · 16:00–00:00",
        conditions: [],
      },
      "pt-BR": {
        title: "20% em todo o cardápio",
        summary: "No pôr do sol sobre a ponte",
        description: "Chope, vinho verde e tábuas de frios com a melhor vista da Ponte Luís I e da Ribeira.",
        schedule: "Todos os dias · 16h–0h",
        conditions: [],
      },
      es: {
        title: "20 % en toda la carta",
        summary: "Con la puesta de sol sobre el puente",
        description: "Cañas, vinho verde y tablas de embutidos con la mejor vista del Puente Luís I y la Ribeira.",
        schedule: "Todos los días · 16:00–00:00",
        conditions: [],
      },
      en: {
        title: "20% off the whole menu",
        summary: "Sunset over the bridge",
        description: "Draught beer, vinho verde and charcuterie boards with the best view of the Luís I Bridge and the Ribeira.",
        schedule: "Every day · 16:00–00:00",
        conditions: [],
      },
    },
  },
  {
    slug: "cervejaria-da-boavista",
    category: "bars",
    zone: "boavista",
    discount: { type: "PERCENT", value: 15 },
    maxPeople: 6,
    art: "bar",
    venue: { name: "Cervejaria da Boavista", address: "Avenida da Boavista 1120", postalCode: "4100-112", city: "Porto", neighbourhood: "Boavista", latitude: 41.1588, longitude: -8.6318 },
    copy: {
      "pt-PT": {
        title: "15% em cerveja artesanal e petiscos",
        summary: "Dias de jogo incluídos",
        description: "Doze torneiras de cerveja artesanal do norte, bifanas e cachorros à moda do Porto.",
        schedule: "Segunda a sábado · 12:00–01:00",
        conditions: [],
      },
      "pt-BR": {
        title: "15% em cerveja artesanal e petiscos",
        summary: "Dias de jogo incluídos",
        description: "Doze torneiras de cerveja artesanal do norte de Portugal, bifanas e cachorros à moda do Porto.",
        schedule: "Segunda a sábado · 12h–1h",
        conditions: [],
      },
      es: {
        title: "15 % en cerveza artesana y tapas",
        summary: "Días de partido incluidos",
        description: "Doce grifos de cerveza artesana del norte, bifanas y perritos al estilo de Oporto.",
        schedule: "De lunes a sábado · 12:00–01:00",
        conditions: [],
      },
      en: {
        title: "15% off craft beer and bar snacks",
        summary: "Match days included",
        description: "Twelve taps of northern craft beer, bifanas and Porto-style hot dogs.",
        schedule: "Monday to Saturday · 12:00–01:00",
        conditions: [],
      },
    },
  },
  {
    slug: "concertos-armazem-do-rio",
    category: "events",
    zone: "ribeira",
    featured: true,
    discount: { type: "PERCENT", value: 25 },
    maxPeople: 2,
    art: "evento",
    venue: { name: "Armazém do Rio", address: "Rua da Arménia 17", postalCode: "4050-063", city: "Porto", neighbourhood: "Miragaia", latitude: 41.1424, longitude: -8.6222 },
    copy: {
      "pt-PT": {
        title: "25% nos bilhetes de concertos",
        summary: "Sextas e sábados",
        description: "Um antigo armazém de bacalhau transformado em sala de concertos: jazz, fado novo e bandas portuguesas em ascensão.",
        schedule: "Sextas e sábados · portas às 21:30",
        conditions: ["Até 2 bilhetes por cartão", "Compra na bilheteira, sujeita a lotação"],
      },
      "pt-BR": {
        title: "25% nos ingressos de shows",
        summary: "Sextas e sábados",
        description: "Um antigo armazém de bacalhau transformado em casa de shows: jazz, fado novo e bandas portuguesas em ascensão.",
        schedule: "Sextas e sábados · abertura às 21h30",
        conditions: ["Até 2 ingressos por cartão", "Compra na bilheteria, sujeita à lotação"],
      },
      es: {
        title: "25 % en entradas de conciertos",
        summary: "Viernes y sábados",
        description: "Un antiguo almacén de bacalao convertido en sala de conciertos: jazz, fado nuevo y bandas portuguesas emergentes.",
        schedule: "Viernes y sábados · apertura de puertas a las 21:30",
        conditions: ["Hasta 2 entradas por tarjeta", "Compra en taquilla, según aforo"],
      },
      en: {
        title: "25% off gig tickets",
        summary: "Fridays and Saturdays",
        description: "An old salt cod warehouse turned music venue: jazz, new fado and up-and-coming Portuguese bands.",
        schedule: "Fridays and Saturdays · doors at 21:30",
        conditions: ["Up to 2 tickets per card", "Buy at the box office, subject to capacity"],
      },
    },
  },
  {
    slug: "noites-de-fado-da-se",
    category: "events",
    zone: "ribeira",
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 2,
    art: "evento",
    venue: { name: "Casa de Fado da Sé", address: "Rua de Dom Hugo 9", postalCode: "4050-305", city: "Porto", neighbourhood: "Sé", latitude: 41.1426, longitude: -8.6115 },
    copy: {
      "pt-PT": {
        title: "20% nas noites de fado",
        summary: "Bilhete com copo de vinho do Porto",
        description: "Fado à luz das velas numa casa do século XVIII junto à Sé, com guitarra portuguesa e viola.",
        schedule: "Quarta a domingo · 21:00 e 22:30",
        conditions: ["Até 2 bilhetes por cartão", "Reserva obrigatória"],
      },
      "pt-BR": {
        title: "20% nas noites de fado",
        summary: "Ingresso com taça de vinho do Porto",
        description: "Fado à luz de velas numa casa do século XVIII ao lado da Sé, com guitarra portuguesa e violão.",
        schedule: "Quarta a domingo · 21h e 22h30",
        conditions: ["Até 2 ingressos por cartão", "Reserva obrigatória"],
      },
      es: {
        title: "20 % en las noches de fado",
        summary: "Entrada con copa de oporto",
        description: "Fado a la luz de las velas en una casa del siglo XVIII junto a la catedral, con guitarra portuguesa y guitarra clásica.",
        schedule: "De miércoles a domingo · 21:00 y 22:30",
        conditions: ["Hasta 2 entradas por tarjeta", "Reserva obligatoria"],
      },
      en: {
        title: "20% off fado nights",
        summary: "Ticket includes a glass of port",
        description: "Candlelit fado in an 18th-century house beside the cathedral, with Portuguese guitar and classical guitar.",
        schedule: "Wednesday to Sunday · 21:00 and 22:30",
        conditions: ["Up to 2 tickets per card", "Booking required"],
      },
    },
  },
  {
    slug: "cinema-na-praia",
    category: "events",
    zone: "foz",
    discount: { type: "PERCENT", value: 30 },
    maxPeople: 2,
    art: "evento",
    venue: { name: "Cinema na Praia", address: "Praia de Matosinhos, Avenida Norton de Matos", postalCode: "4450-208", city: "Matosinhos", neighbourhood: "Matosinhos", latitude: 41.1769, longitude: -8.6889 },
    copy: {
      "pt-PT": {
        title: "30% nas sessões de cinema ao ar livre",
        summary: "Espreguiçadeira e manta incluídas",
        description: "Clássicos e estreias recentes projetados no areal, com o som das ondas como banda sonora extra.",
        schedule: "Quinta a sábado · sessão às 21:45",
        conditions: ["Até 2 bilhetes por cartão", "Sessões sujeitas ao tempo"],
      },
      "pt-BR": {
        title: "30% nas sessões de cinema ao ar livre",
        summary: "Espreguiçadeira e manta incluídas",
        description: "Clássicos e lançamentos projetados na areia, com o barulho das ondas como trilha sonora extra.",
        schedule: "Quinta a sábado · sessão às 21h45",
        conditions: ["Até 2 ingressos por cartão", "Sessões sujeitas ao tempo"],
      },
      es: {
        title: "30 % en las sesiones de cine al aire libre",
        summary: "Tumbona y manta incluidas",
        description: "Clásicos y estrenos recientes proyectados en la arena, con el sonido de las olas como banda sonora extra.",
        schedule: "De jueves a sábado · sesión a las 21:45",
        conditions: ["Hasta 2 entradas por tarjeta", "Sesiones sujetas al tiempo"],
      },
      en: {
        title: "30% off open-air cinema",
        summary: "Deckchair and blanket included",
        description: "Classics and recent releases screened on the sand, with the waves as an extra soundtrack.",
        schedule: "Thursday to Saturday · screening at 21:45",
        conditions: ["Up to 2 tickets per card", "Weather permitting"],
      },
    },
  },
  {
    slug: "oficina-de-azulejo",
    category: "culture",
    zone: "ribeira",
    featured: true,
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 2,
    art: "cultura",
    venue: { name: "Oficina de Azulejo", address: "Rua do Bonfim 140", postalCode: "4300-069", city: "Porto", neighbourhood: "Bonfim", latitude: 41.1478, longitude: -8.5962 },
    copy: {
      "pt-PT": {
        title: "20% nos workshops de pintura de azulejo",
        summary: "Leva o teu azulejo para casa",
        description: "Três horas a pintar azulejo à mão com técnicas tradicionais. O forno trata do resto e o azulejo fica pronto numa semana.",
        schedule: "Sábados · 10:00 e 15:00",
        conditions: ["Até 2 inscrições por cartão", "Inscrição prévia obrigatória"],
      },
      "pt-BR": {
        title: "20% nas oficinas de pintura de azulejo",
        summary: "Leve o seu azulejo para casa",
        description: "Três horas pintando azulejo à mão com técnicas tradicionais. O forno cuida do resto e o azulejo fica pronto em uma semana.",
        schedule: "Sábados · 10h e 15h",
        conditions: ["Até 2 inscrições por cartão", "Inscrição prévia obrigatória"],
      },
      es: {
        title: "20 % en los talleres de pintura de azulejo",
        summary: "Llévate tu azulejo a casa",
        description: "Tres horas pintando azulejo a mano con técnicas tradicionales. El horno hace el resto y el azulejo está listo en una semana.",
        schedule: "Sábados · 10:00 y 15:00",
        conditions: ["Hasta 2 inscripciones por tarjeta", "Inscripción previa obligatoria"],
      },
      en: {
        title: "20% off azulejo painting workshops",
        summary: "Take your tile home",
        description: "Three hours hand-painting tiles with traditional techniques. The kiln does the rest and your tile is ready in a week.",
        schedule: "Saturdays · 10:00 and 15:00",
        conditions: ["Up to 2 places per card", "Booking required"],
      },
    },
  },
  {
    slug: "porto-a-pe",
    category: "culture",
    zone: "ribeira",
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 4,
    art: "ribeira",
    venue: { name: "Porto a Pé", address: "Praça da Ribeira 1", postalCode: "4050-513", city: "Porto", neighbourhood: "Ribeira", latitude: 41.1406, longitude: -8.6133 },
    copy: {
      "pt-PT": {
        title: "20% nas visitas guiadas a pé",
        summary: "Duas horas pela cidade antiga",
        description: "Da Ribeira à Sé pelas escadinhas, com histórias de comerciantes, cheias do rio e azulejos escondidos.",
        schedule: "Todos os dias · 10:30 e 16:00",
        conditions: ["Visitas em português, inglês e espanhol"],
      },
      "pt-BR": {
        title: "20% nos passeios guiados a pé",
        summary: "Duas horas pela cidade antiga",
        description: "Da Ribeira à Sé pelas escadarias, com histórias de comerciantes, cheias do rio e azulejos escondidos.",
        schedule: "Todos os dias · 10h30 e 16h",
        conditions: ["Passeios em português, inglês e espanhol"],
      },
      es: {
        title: "20 % en las visitas guiadas a pie",
        summary: "Dos horas por la ciudad antigua",
        description: "De la Ribeira a la catedral por las escalinatas, con historias de comerciantes, crecidas del río y azulejos escondidos.",
        schedule: "Todos los días · 10:30 y 16:00",
        conditions: ["Visitas en portugués, inglés y español"],
      },
      en: {
        title: "20% off guided walking tours",
        summary: "Two hours through the old town",
        description: "From the Ribeira up the steps to the cathedral, with stories of merchants, river floods and hidden tiles.",
        schedule: "Every day · 10:30 and 16:00",
        conditions: ["Tours in Portuguese, English and Spanish"],
      },
    },
  },
  {
    slug: "livraria-do-largo",
    category: "culture",
    zone: "boavista",
    discount: { type: "PERCENT", value: 10 },
    art: "cultura",
    venue: { name: "Livraria do Largo", address: "Rua do Breiner 85", postalCode: "4050-126", city: "Porto", neighbourhood: "Cedofeita", latitude: 41.1497, longitude: -8.6182 },
    copy: {
      "pt-PT": {
        title: "10% em livros e discos",
        summary: "Exceto novidades da semana",
        description: "Livraria independente com segunda mão escolhida a dedo, vinil português e um canto de leitura com café.",
        schedule: "Segunda a sábado · 10:00–20:00",
        conditions: ["Não inclui novidades da semana", "Não acumula com outros descontos"],
      },
      "pt-BR": {
        title: "10% em livros e discos",
        summary: "Exceto lançamentos da semana",
        description: "Livraria independente com usados escolhidos a dedo, vinil português e um cantinho de leitura com café.",
        schedule: "Segunda a sábado · 10h–20h",
        conditions: ["Não inclui lançamentos da semana", "Não cumulativo com outros descontos"],
      },
      es: {
        title: "10 % en libros y discos",
        summary: "Excepto novedades de la semana",
        description: "Librería independiente con segunda mano elegida con mimo, vinilo portugués y un rincón de lectura con café.",
        schedule: "De lunes a sábado · 10:00–20:00",
        conditions: ["No incluye novedades de la semana", "No acumulable con otros descuentos"],
      },
      en: {
        title: "10% off books and records",
        summary: "Except this week's new releases",
        description: "An independent bookshop with hand-picked second-hand books, Portuguese vinyl and a reading corner with coffee.",
        schedule: "Monday to Saturday · 10:00–20:00",
        conditions: ["Excludes this week's new releases", "Can't be combined with other discounts"],
      },
    },
  },
  {
    slug: "escola-de-surf-norte",
    category: "leisure",
    zone: "foz",
    featured: true,
    discount: { type: "AMOUNT", value: 10 },
    art: "surf",
    venue: { name: "Escola de Surf Norte", address: "Avenida General Norton de Matos 22", postalCode: "4450-208", city: "Matosinhos", neighbourhood: "Matosinhos", latitude: 41.1756, longitude: -8.6878 },
    copy: {
      "pt-PT": {
        title: "10 € de desconto em aulas de surf",
        summary: "Prancha e fato incluídos",
        description: "Aulas de duas horas para iniciantes e intermédios na praia de Matosinhos, com instrutores certificados.",
        schedule: "Todos os dias · 09:00–18:00",
        conditions: ["Uma aula com desconto por cartão por semana", "Marcação prévia"],
      },
      "pt-BR": {
        title: "10 € de desconto em aulas de surfe",
        summary: "Prancha e roupa de neoprene incluídas",
        description: "Aulas de duas horas para iniciantes e intermediários na praia de Matosinhos, com instrutores certificados.",
        schedule: "Todos os dias · 9h–18h",
        conditions: ["Uma aula com desconto por cartão por semana", "Agendamento prévio"],
      },
      es: {
        title: "10 € de descuento en clases de surf",
        summary: "Tabla y neopreno incluidos",
        description: "Clases de dos horas para principiantes e intermedios en la playa de Matosinhos, con monitores titulados.",
        schedule: "Todos los días · 09:00–18:00",
        conditions: ["Una clase con descuento por tarjeta y semana", "Reserva previa"],
      },
      en: {
        title: "€10 off surf lessons",
        summary: "Board and wetsuit included",
        description: "Two-hour lessons for beginners and improvers on Matosinhos beach, with certified instructors.",
        schedule: "Every day · 09:00–18:00",
        conditions: ["One discounted lesson per card per week", "Booking required"],
      },
    },
  },
  {
    slug: "rabelo-ao-por-do-sol",
    category: "leisure",
    zone: "ribeira",
    discount: { type: "PERCENT", value: 30 },
    maxPeople: 4,
    art: "ribeira",
    venue: { name: "Rabelo ao Pôr do Sol", address: "Cais da Ribeira 34", postalCode: "4050-510", city: "Porto", neighbourhood: "Cais da Ribeira", latitude: 41.1402, longitude: -8.6125 },
    copy: {
      "pt-PT": {
        title: "30% no cruzeiro das seis pontes",
        summary: "Cinquenta minutos no Douro",
        description: "Num barco rabelo tradicional, passa por baixo das seis pontes do Porto à hora dourada.",
        schedule: "Todos os dias · saídas de hora a hora, 10:00–19:00",
        conditions: ["Sujeito às condições do rio"],
      },
      "pt-BR": {
        title: "30% no passeio das seis pontes",
        summary: "Cinquenta minutos no Douro",
        description: "Num barco rabelo tradicional, passe por baixo das seis pontes do Porto na hora dourada.",
        schedule: "Todos os dias · saídas de hora em hora, 10h–19h",
        conditions: ["Sujeito às condições do rio"],
      },
      es: {
        title: "30 % en el crucero de los seis puentes",
        summary: "Cincuenta minutos por el Duero",
        description: "En un barco rabelo tradicional, pasa bajo los seis puentes de Oporto a la hora dorada.",
        schedule: "Todos los días · salidas cada hora, 10:00–19:00",
        conditions: ["Sujeto al estado del río"],
      },
      en: {
        title: "30% off the six bridges cruise",
        summary: "Fifty minutes on the Douro",
        description: "Glide under Porto's six bridges at golden hour aboard a traditional rabelo boat.",
        schedule: "Every day · hourly departures, 10:00–19:00",
        conditions: ["Subject to river conditions"],
      },
    },
  },
  {
    slug: "bicicletas-da-foz",
    category: "leisure",
    zone: "foz",
    discount: { type: "PERCENT", value: 20 },
    maxPeople: 4,
    art: "surf",
    venue: { name: "Bicicletas da Foz", address: "Rua do Passeio Alegre 600", postalCode: "4150-573", city: "Porto", neighbourhood: "Foz do Douro", latitude: 41.1478, longitude: -8.6707 },
    copy: {
      "pt-PT": {
        title: "20% no aluguer de bicicletas",
        summary: "Da Foz a Matosinhos pela marginal",
        description: "Bicicletas clássicas e elétricas para percorrer a marginal atlântica, com cadeado e capacete incluídos.",
        schedule: "Todos os dias · 09:30–19:30",
        conditions: ["Até 4 bicicletas por cartão", "Documento de identificação obrigatório"],
      },
      "pt-BR": {
        title: "20% no aluguel de bicicletas",
        summary: "Da Foz a Matosinhos pela orla",
        description: "Bicicletas clássicas e elétricas para percorrer a orla atlântica, com cadeado e capacete incluídos.",
        schedule: "Todos os dias · 9h30–19h30",
        conditions: ["Até 4 bicicletas por cartão", "Documento de identidade obrigatório"],
      },
      es: {
        title: "20 % en el alquiler de bicicletas",
        summary: "De Foz a Matosinhos por el paseo marítimo",
        description: "Bicicletas clásicas y eléctricas para recorrer el paseo atlántico, con candado y casco incluidos.",
        schedule: "Todos los días · 09:30–19:30",
        conditions: ["Hasta 4 bicicletas por tarjeta", "Documento de identidad obligatorio"],
      },
      en: {
        title: "20% off bike hire",
        summary: "From Foz to Matosinhos along the seafront",
        description: "Classic and electric bikes for the Atlantic promenade, with lock and helmet included.",
        schedule: "Every day · 09:30–19:30",
        conditions: ["Up to 4 bikes per card", "Photo ID required"],
      },
    },
  },
  {
    slug: "jardins-da-serra",
    category: "leisure",
    zone: "gaia",
    discount: { type: "PERCENT", value: 25 },
    maxPeople: 2,
    art: "cafe",
    venue: { name: "Jardins da Serra Spa", address: "Rua Cândido dos Reis 410", postalCode: "4400-075", city: "Vila Nova de Gaia", neighbourhood: "Gaia", latitude: 41.1335, longitude: -8.6118 },
    copy: {
      "pt-PT": {
        title: "25% em massagens e circuito de spa",
        summary: "De segunda a sexta",
        description: "Banho turco, piscina interior e massagens de 50 minutos num jardim escondido a dois passos das caves.",
        schedule: "Segunda a sexta · 10:00–21:00",
        conditions: ["Marcação prévia"],
      },
      "pt-BR": {
        title: "25% em massagens e circuito de spa",
        summary: "De segunda a sexta",
        description: "Banho turco, piscina coberta e massagens de 50 minutos num jardim escondido a poucos passos das adegas.",
        schedule: "Segunda a sexta · 10h–21h",
        conditions: ["Agendamento prévio"],
      },
      es: {
        title: "25 % en masajes y circuito de spa",
        summary: "De lunes a viernes",
        description: "Baño turco, piscina interior y masajes de 50 minutos en un jardín escondido a dos pasos de las bodegas.",
        schedule: "De lunes a viernes · 10:00–21:00",
        conditions: ["Reserva previa"],
      },
      en: {
        title: "25% off massages and spa circuit",
        summary: "Monday to Friday",
        description: "Steam room, indoor pool and 50-minute massages in a hidden garden a short walk from the port cellars.",
        schedule: "Monday to Friday · 10:00–21:00",
        conditions: ["Booking required"],
      },
    },
  },
];
